name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: gerlero/apt-install@v1
      with:
          packages: meson libcairo2-dev pkg-config python3-dev
    - uses: actions/checkout@v4

    - name: Build font
      run: make build

    - name: Build proof
      run: make proof

    - name: Build tests
      run: make test

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
        draft: false
        prerelease: true
