name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: gerlero/apt-install@v1
      with:
          packages: meson libcairo2-dev pkg-config python3-dev
    - uses: actions/checkout@v4

    - name: build font
      run: make build

    - name: make proof
      run: make proof

    - name: build tests
      run: make test
