name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: gerlero/apt-install@v1
      with:
          packages: pkg-config meson
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make build
